# Generated by Django 5.0.6 on 2024-11-20 04:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empleados', '0006_empleado_user'),
        ('proveedores', '0002_alter_proveedor_email_empresa_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_pedido', models.DateField(verbose_name='Fecha de pedido')),
                ('estado', models.CharField()),
                ('fecha_entrega', models.DateField(verbose_name='Fecha de entrega')),
                ('observaciones', models.TextField(default='Sin observaciones')),
                ('departamento', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='empleados.empleado')),
                ('proveedor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='proveedores.proveedor')),
            ],
            options={
                'verbose_name': 'Pedido',
                'verbose_name_plural': 'Pedidos',
            },
        ),
    ]
