# Generated by Django 5.0.6 on 2024-11-21 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos_compras', '0002_rename_departamento_pedido_empleado'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='activo',
            field=models.BooleanField(default=True),
        ),
    ]
