# Generated by Django 5.0.6 on 2024-11-21 16:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos_compras', '0005_alter_pedido_observaciones'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='fecha_entrega',
            field=models.DateField(default=datetime.datetime(2024, 11, 21, 16, 31, 25, 674309, tzinfo=datetime.timezone.utc), verbose_name='Fecha de entrega'),
        ),
    ]
