# Generated by Django 5.0.6 on 2024-11-21 16:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos_compras', '0006_alter_pedido_fecha_entrega'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='fecha_entrega',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de entrega'),
        ),
    ]
