# Generated by Django 5.0.6 on 2024-10-02 17:03

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('almacen_productos', '0011_remove_producto_descripcion_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MetodosPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_venta', models.DateField(default=datetime.date.today, verbose_name='Fecha de la venta')),
                ('subtotal', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Subtotal')),
                ('porcentaje_iva', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Porcentaje de IVA')),
                ('precio_iva', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Precio del IVA')),
                ('porcentaje_descuento', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Porcentaje de Descuento')),
                ('precio_descuento', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Precio del Descuento')),
                ('total', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Total')),
                ('monto_recibido', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Monto recibido')),
                ('cambio', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Cambio')),
                ('metodo_pago', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ventas.metodospago', verbose_name='Método de pago')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
        ),
        migrations.CreateModel(
            name='ProductosVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(verbose_name='Cantidad')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='almacen_productos.producto', verbose_name='Producto')),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ventas.venta', verbose_name='Venta')),
            ],
        ),
    ]
