# Generated by Django 5.0.6 on 2024-10-25 17:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=50)),
                ('apellidos', models.CharField(max_length=50)),
                ('fecha_nacimiento', models.DateField()),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=1)),
                ('direccion', models.TextField(verbose_name='Dirección')),
                ('telefono', models.IntegerField(max_length=10)),
                ('grupo_sanguineo', models.CharField(max_length=3)),
                ('fecha_contratacion', models.DateField()),
                ('fecha_alta_ss', models.DateField()),
                ('nss', models.IntegerField(max_length=11)),
                ('clabe_interbancaria', models.IntegerField(max_length=18)),
                ('contacto_emergencia_nombres', models.TextField(max_length=50)),
                ('contacto_emergencia_apellidos', models.TextField(max_length=50)),
                ('contacto_emergencia_telefono', models.IntegerField(max_length=10)),
                ('contacto_emergencia_parentesco', models.CharField(choices=[('Madre', 'Madre'), ('Padre', 'Padre'), ('Hermano(a)', 'Hermano(a)'), ('Esposo(a)', 'Esposo(a)'), ('Novio(a)', 'Novio(a)'), ('Otro', 'Otro')], max_length=10)),
                ('activo', models.BooleanField(default=True)),
                ('eliminado', models.BooleanField(default=False)),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empleados.departamento')),
                ('puesto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empleados.puesto')),
            ],
            options={
                'verbose_name': 'Empleado',
                'verbose_name_plural': 'Empleados',
            },
        ),
    ]
