# Generated by Django 5.0.6 on 2024-10-25 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0002_empleado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='clabe_interbancaria',
            field=models.CharField(max_length=18, verbose_name='CLABE interbancaria'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='contacto_emergencia_apellidos',
            field=models.CharField(max_length=50, verbose_name='Apellidos de contacto de emergencia'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='contacto_emergencia_nombres',
            field=models.CharField(max_length=50, verbose_name='Nombres de contacto de emergencia'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='contacto_emergencia_parentesco',
            field=models.CharField(choices=[('Madre', 'Madre'), ('Padre', 'Padre'), ('Hermano(a)', 'Hermano(a)'), ('Esposo(a)', 'Esposo(a)'), ('Novio(a)', 'Novio(a)'), ('Otro', 'Otro')], max_length=10, verbose_name='Parentesco de contacto de emergencia'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='contacto_emergencia_telefono',
            field=models.CharField(max_length=10, verbose_name='Teléfono de contacto de emergencia'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='fecha_alta_ss',
            field=models.DateField(verbose_name='Fecha de alta en SS'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='fecha_contratacion',
            field=models.DateField(verbose_name='Fecha de contratación'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='grupo_sanguineo',
            field=models.CharField(max_length=3, verbose_name='Grupo sanguíneo'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='nss',
            field=models.CharField(max_length=11, verbose_name='NSS'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='telefono',
            field=models.CharField(max_length=10, verbose_name='Teléfono'),
        ),
    ]
