# Generated by Django 5.0.6 on 2024-10-30 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0003_alter_empleado_clabe_interbancaria_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='contacto_emergencia_parentesco',
            field=models.CharField(choices=[('Madre', 'Madre'), ('Padre', 'Padre'), ('Hermanos', 'Hermano(a)'), ('Esposos', 'Esposo(a)'), ('Novios', 'Novio(a)'), ('Otro', 'Otro')], max_length=10, verbose_name='Parentesco de contacto de emergencia'),
        ),
    ]
