# Generated by Django 5.0.6 on 2024-10-31 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0004_alter_empleado_contacto_emergencia_parentesco'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='grupo_sanguineo',
            field=models.CharField(choices=[('A-', 'A-'), ('A+', 'A+'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=3, verbose_name='Grupo sanguíneo'),
        ),
    ]
