# Generated by Django 5.0.6 on 2024-09-23 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('almacen_productos', '0002_alter_producto_categoria_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='categoria_id',
            new_name='categoria',
        ),
    ]
