# Generated by Django 5.0.6 on 2024-09-27 16:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almacen_productos', '0003_rename_categoria_id_producto_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='almacen_productos.categoria', verbose_name='Categoría'),
        ),
    ]
