# Generated by Django 5.0.6 on 2024-09-27 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almacen_productos', '0004_alter_producto_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='nombre',
            field=models.CharField(max_length=50),
        ),
    ]
