# Generated by Django 5.0.6 on 2024-10-01 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almacen_productos', '0006_alter_categoria_options_alter_producto_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='precio_venta',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio de Venta'),
        ),
    ]
