# Generated by Django 5.0.6 on 2024-10-01 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almacen_productos', '0007_alter_producto_precio_venta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='descripcion',
            field=models.TextField(blank=True, default='Sin descripción', null=True, verbose_name='Descripción'),
        ),
    ]
