# Generated by Django 5.0.6 on 2024-10-02 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almacen_productos', '0011_remove_producto_descripcion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='stock_maximo',
            field=models.IntegerField(verbose_name='Stock máximo'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='stock_minimo',
            field=models.IntegerField(verbose_name='Stock mínimo'),
        ),
    ]
