# Generated by Django 5.0.6 on 2024-10-13 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almacen_productos', '0013_remove_producto_stock_maximo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='descripcion',
            field=models.TextField(blank=True, default='Sin descripción', verbose_name='Descripción'),
        ),
    ]
