# Generated by Django 5.0.6 on 2024-10-14 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_alter_cliente_genero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='fecha_ultima_compra',
            field=models.DateField(blank=True, null=True, verbose_name='Última compra'),
        ),
    ]
