# Generated by Django 5.0.6 on 2024-10-14 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0004_alter_cliente_fecha_ultima_compra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='email',
            field=models.EmailField(blank=True, max_length=60, null=True),
        ),
    ]
