# Generated by Django 5.0.6 on 2024-10-25 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0005_alter_cliente_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='eliminado',
            field=models.BooleanField(default=False),
        ),
    ]
