# Generated by Django 5.0.6 on 2024-11-19 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almacen', '0003_insumo_sku'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insumo',
            name='sku',
            field=models.CharField(max_length=12),
        ),
    ]
