# Generated by Django 5.0.6 on 2024-11-20 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almacen', '0004_alter_insumo_sku'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='insumo',
            name='stock',
        ),
        migrations.AddField(
            model_name='insumo',
            name='stock_actual',
            field=models.IntegerField(default=16, verbose_name='Stock actual'),
        ),
        migrations.AddField(
            model_name='insumo',
            name='stock_minimo',
            field=models.IntegerField(default=7, verbose_name='Stock mínimo'),
        ),
    ]
