# Generated by Django 5.0.6 on 2024-11-20 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almacen', '0005_remove_insumo_stock_insumo_stock_actual_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insumo',
            name='stock_actual',
            field=models.IntegerField(verbose_name='Stock actual'),
        ),
        migrations.AlterField(
            model_name='insumo',
            name='stock_minimo',
            field=models.IntegerField(verbose_name='Stock mínimo'),
        ),
    ]
