# Generated by Django 5.0.6 on 2024-11-20 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almacen', '0006_alter_insumo_stock_actual_alter_insumo_stock_minimo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insumo',
            name='stock_actual',
            field=models.IntegerField(default=0, verbose_name='Stock actual'),
        ),
    ]
