# Generated by Django 5.0.6 on 2024-11-20 05:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almacen', '0007_alter_insumo_stock_actual'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='stock',
        ),
        migrations.AddField(
            model_name='insumo',
            name='precio_promedio',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='producto',
            name='costo_promedio',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='producto',
            name='fecha_ingreso',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='producto',
            name='ganancia',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='producto',
            name='iva',
            field=models.DecimalField(decimal_places=2, default=16, max_digits=10),
        ),
        migrations.AddField(
            model_name='producto',
            name='sku',
            field=models.CharField(default='111', max_length=12),
        ),
        migrations.AddField(
            model_name='producto',
            name='stock_actual',
            field=models.IntegerField(default=0, verbose_name='Stock actual'),
        ),
        migrations.AddField(
            model_name='producto',
            name='stock_minimo',
            field=models.IntegerField(default=4, verbose_name='Stock mínimo'),
        ),
    ]
