# Generated by Django 5.0.6 on 2024-11-20 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almacen', '0008_remove_producto_stock_insumo_precio_promedio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='ganancia',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='producto',
            name='sku',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='producto',
            name='stock_minimo',
            field=models.IntegerField(verbose_name='Stock mínimo'),
        ),
    ]
