# Generated by Django 5.0.6 on 2024-11-08 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_empresa', models.CharField(max_length=100, verbose_name='Nombre de la empresa')),
                ('rfc', models.CharField(max_length=13, verbose_name='RFC')),
                ('direccion', models.TextField(verbose_name='Dirección')),
                ('telefono_empresa', models.CharField(max_length=12, verbose_name='Teléfono de la empresa')),
                ('email_empresa', models.CharField(max_length=12, verbose_name='Email de la empresa')),
                ('tipo_persona', models.CharField(choices=[('Moral', 'Moral'), ('Fisica', 'Física')], max_length=6, verbose_name='Tipo de persona')),
                ('banco', models.CharField(max_length=100, verbose_name='Nombre del banco')),
                ('numero_cuenta', models.CharField(max_length=100, verbose_name='Número de cuenta')),
                ('representante_nombres', models.CharField(max_length=50, verbose_name='Nombre del representante')),
                ('representante_apellidos', models.CharField(max_length=50, verbose_name='Apellidos del representante')),
                ('representante_sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=9, verbose_name='Sexo del representante')),
                ('representante_telefono', models.CharField(max_length=10, verbose_name='Teléfono del representante')),
                ('representante_email', models.CharField(max_length=50, verbose_name='Email del representante')),
                ('activo', models.BooleanField(default=True)),
                ('eliminado', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
            },
        ),
    ]
