# Generated by Django 5.0.6 on 2024-11-05 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Provedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_empresa', models.CharField(max_length=100, verbose_name='Nombre de la empresa')),
                ('rfc', models.CharField(max_length=13, verbose_name='RFC')),
                ('direccion_fiscal', models.TextField(verbose_name='Dirección fiscal')),
                ('direccion_envio', models.TextField(verbose_name='Dirección de envío')),
                ('tipo_persona', models.CharField(choices=[('Moral', 'Moral'), ('Fisica', 'Física')], max_length=6, verbose_name='Tipo de persona')),
                ('contacto_nombres', models.CharField(max_length=50, verbose_name='Nombre del contacto')),
                ('contacto_apellidos', models.CharField(max_length=50, verbose_name='Apellidos del contacto')),
                ('contacto_sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=9, verbose_name='Sexo del contacto')),
                ('contacto_telefono', models.CharField(max_length=10, verbose_name='Teléfono del contacto')),
                ('contacto_email', models.CharField(max_length=50, verbose_name='Email del contacto')),
                ('activo', models.BooleanField(default=True)),
                ('eliminado', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Provedor',
                'verbose_name_plural': 'Provedores',
            },
        ),
    ]
