# Generated by Django 5.0.6 on 2024-11-08 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proveedor',
            name='email_empresa',
            field=models.CharField(max_length=50, verbose_name='Email de la empresa'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='numero_cuenta',
            field=models.CharField(max_length=18, verbose_name='Número de cuenta'),
        ),
    ]
